# Generated by Django 4.2 on 2024-02-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteversion',
            name='changes',
        ),
    ]
